esphome:
  name: wasserzahler
  friendly_name: Wasserzähler

esp8266:
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
api:
ota:
  platform: esphome




# -------------------------------------------------
# EINSTELLUNGEN (NUMBERS)
# -------------------------------------------------
number:
  # Zeit in Minuten, bis der Alarm auslöst
  - platform: template
    name: "Alarm Verzögerung"
    id: leak_alarm_threshold
    unit_of_measurement: "min"
    icon: "mdi:clock-alert-outline"
    min_value: 1
    max_value: 999
    step: 1
    initial_value: 120
    restore_value: true
    set_action:
      - lambda: id(leak_alarm_threshold).publish_state(x);

# -------------------------------------------------
# SKRIPTE (LOGIK)
# -------------------------------------------------
script:
  - id: leak_timer_script
    mode: single
    then:
      - delay: !lambda "return id(leak_alarm_threshold).state * 60000;"
      - binary_sensor.template.publish:
          id: water_leak_alarm
          state: ON

# -------------------------------------------------
# BUTTONS
# -------------------------------------------------
button:
  - platform: restart
    name: "ESP Gerät Neustart"
    icon: "mdi:power-cycle"


# -------------------------------------------------
# SENSOREN
# -------------------------------------------------
sensor:

  - platform: pulse_meter
    pin: GPIO14
    id: water_flow
    name: "Wasserdurchfluss"
    unit_of_measurement: "l/min"
    icon: "mdi:water"
    accuracy_decimals: 1
    internal_filter: 50ms
    timeout: 180s
    internal_filter_mode: PULSE
    on_value:
      then:
        - if:
            condition:
              lambda: 'return x > 0.0;'
            then:
              - script.execute: leak_timer_script
            else:
              - script.stop: leak_timer_script
              - binary_sensor.template.publish:
                  id: water_leak_alarm
                  state: OFF
    total:
      id: water_total_liter
      unit_of_measurement: "l"
      accuracy_decimals: 1

  # Hauptanzeige in m³
  - platform: template
    name: "Wasserverbrauch Impulse"
    unit_of_measurement: "m³"
    device_class: water
    state_class: total_increasing
    accuracy_decimals: 4
    icon: "mdi:water-pump"
    lambda: |-
      return id(water_total_liter).state /1000.0;

  # Zweitanzeige in Litern
  - platform: template
    name: "Wasserverbrauch Impulse Liter"
    unit_of_measurement: "L"
    device_class: water
    state_class: total_increasing
    accuracy_decimals: 1
    icon: "mdi:water-pump"
    lambda: |-
      return id(water_total_liter).state;


# -------------------------------------------------
# BINARY SENSORS (ALARM)
# -------------------------------------------------
binary_sensor:
  - platform: template
    name: "Wasser Leckage Alarm"
    id: water_leak_alarm
    device_class: problem
    icon: "mdi:alarm-light-off"
    on_state:
      - lambda: |-
          if (x) {
            id(water_leak_alarm).set_icon("mdi:alarm-light");
          } else {
            id(water_leak_alarm).set_icon("mdi:alarm-light-off");
          }